language: python

cache:
  pip: true
  directories:
  - "$HOME/.cache/pipenv"

env:
  - PIPENV_CACHE_DIR="$HOME/.cache/pipenv"

stages:
  - linting
  - test

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest

jobs:
  include:
    - python: "3.7"
      dist: xenial

    - stage: linting
      python: "3.7"
      dist: xenial
      script: pipenv run flake8
